baseURL: https://dfennessey.com/
languageCode: en-us
title: dfennessey.com
theme: "PaperMod"
paginate: 5

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

taxonomies:
  projects: projects
  blogs: blogs

googleAnalytics: G-KS4P05R98L

minify:
    disableXML: true
    minifyOutput: false

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: ExampleSite
    description: "ExampleSite description"
    keywords: [Blog, Portfolio, PaperMod]
    author: Me
    images: ["<link or path of image for opengraph, twitter-cards>"]
    DateFormat: "January 2, 2006"
    defaultTheme: auto # dark, light
    disableThemeToggle: false

    ShowReadingTime: true
    ShowBreadCrumbs: true
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: false
    tocopen: false

    assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: "<link / abs url>"
        favicon16x16: "<link / abs url>"
        favicon32x32: "<link / abs url>"
        apple_touch_icon: "<link / abs url>"
        safari_pinned_tab: "<link / abs url>"

    label:
        text: "Home"
        icon: /apple-touch-icon.png
        iconHeight: 35

    # profile-mode
    profileMode:
        enabled: false # needs to be explicitly set
        title: ExampleSite
        subtitle: "This is subtitle"
        imageUrl: "<img location>"
        imageWidth: 120
        imageHeight: 120
        imageTitle: my image
        buttons:
            - name: Posts
              url: posts
            - name: Tags
              url: tags

    label:
        text: "dfennessey.com"


    # home-info mode
    homeInfoParams:
        Title: "Hi there \U0001F44B"
        Content: >
            My name is Dave Fennessey. I'm a professional software developer working on the Search team at Wayfair.com. My goal 
            is to never stop learning to be a better engineer, data scientist, photographer, and linguist. 

    socialIcons:
        - name: linkedin
          url: "https://www.linkedin.com/in/david-fennessey/"
        - name: github
          url: "https://github.com/herrfennessey"

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
menu:
    main:
        - identifier: projects
          name: projects
          url: /projects/
          weight: 10
        - identifier: blogs
          name: blogs
          url: /blogs/
          weight: 20
        - identifier: contact
          name: contact
          url: /contact
          weight: 30